setup: |
  echo "üêä Start to install dependencies ..."
  echo "üêä Note: Will not install dependencies if available"
  cd lcsfinder && poetry install
  echo "üêä ... Done installing dependencies"
---

# Checks on Files {{{

# perform checks on a file
- lcsfinder/lcsfinder/__init__.py:
    - description: Ensure that the __init__.py file exists in the lcsfinder/lcsfinder/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for __init__.py in the lcsfinder/ directory
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

# perform checks on a file
- lcsfinder/tests/__init__.py:
    - description: Ensure that the __init__.py file exists in the lcsfinder/tests/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for __init__.py in the tests/ directory
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

# perform checks on a file
- lcsfinder/lcsfinder/main.py:
    - description: Ensure that the main.py file exists in the lcsfinder/lcsfinder/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for main.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in main.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 2
        exact: false
    - description: Create a sufficient number of single-line comments in main.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 5
        exact: false

# perform checks on a file
- lcsfinder/lcsfinder/approach.py:
    - description: Ensure that the approach.py file exists in the lcsfinder/lcsfinder/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for approach.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in approach.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 6
        exact: false

# perform checks on a file
- lcsfinder/lcsfinder/constants.py:
    - description: Ensure that the constants.py file exists in the lcsfinder/lcsfinder/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for constants.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of single-line comments in constants.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 3
        exact: false
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in constants.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 1
        exact: false

# perform checks on a file
- lcsfinder/lcsfinder/generate.py:
    - description: Ensure that the generate.py file exists in the lcsfinder/lcsfinder/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for generate.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in generate.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 2
        exact: false
    - description: Create a sufficient number of single-line comments in generate.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 5
        exact: false

# perform checks on a file
- lcsfinder/lcsfinder/benchmark.py:
    - description: Ensure that the benchmark.py file exists in the lcsfinder/lcsfinder/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for benchmark.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in benchmark.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 7
        exact: false
    - description: Create a sufficient number of single-line comments in benchmark.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 5
        exact: false

# perform checks on a file
- lcsfinder/lcsfinder/lcs.py:
    - description: Ensure that the lcs.py file exists in the lcsfinder/lcsfinder/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for lcs.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in lcs.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 4
        exact: false
    - description: Create a sufficient number of single-line comments in lcs.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 5
        exact: false

# perform checks on a file
- writing/reflection.md:
    - description: Ensure that the reflection.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for the reflection
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the reflection file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true
    - description: Retype the every word in the Honor Code pledge in reflection.md
      check: MatchFileFragment
      options:
        fragment: "I adhered to the Allegheny College Honor Code while completing this project."
        count: 2
        exact: true
    - description: Confirm that the reflection has a subsection for the references
      check: MatchFileFragment
      options:
        fragment: "## References"
        count: 1
        exact: true
    - description: Confirm that the markdown file has the correct number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 17
        exact: false
    - description: Confirm that the markdown file has the correct number of lists of data or commands
      check: CountMarkdownTags
      options:
        tag: list 
        count: 2
        exact: false
    - description: Confirm that the markdown file has the correct number of fenced code blocks
      check: CountMarkdownTags
      options:
        tag: code_block
        count: 4
        exact: false

# }}}

# Check Output {{{

# run a check
- description: Pass the source code linting checks run by mypy
  command: cd lcsfinder && poetry run task mypy

# run a check
- description: Pass the source code formatting checks run by ruff
  command: cd lcsfinder && poetry run task format

# run a check
- description: Pass the source code linting checks run by ruff
  command: cd lcsfinder && poetry run task check

# run a check
- description: Pass the linting checks run by pymarkdown
  command: cd lcsfinder && poetry run task markdownlint

# run a check
- description: Pass the undocumented function checks run by symbex
  command: cd lcsfinder && poetry run task symbex-documented

# run a check
- description: Pass the untyped function checks run by symbex
  command: cd lcsfinder && poetry run task symbex-typed

# }}}

# Program Output {{{

# run the program and confirm correct number of lines in the output
- description: Run the recursive algorithm and confirm the correct number of non-blank lines in the benchmark output
  check: CountCommandOutput
  options:
    command: 'cd lcsfinder && poetry run lcsfinder --algorithmtype recursive --startsize 1 --runs 2 --datatype ints --strategy double'
    count: 10
    exact: false

# run the program and confirm correct number of lines in the output
- description: Run the dynamic algorithm and confirm the correct number of non-blank lines in the benchmark output
  check: CountCommandOutput
  options:
    command: 'cd lcsfinder && poetry run lcsfinder --algorithmtype dynamic --startsize 1 --runs 2 --datatype ints --strategy double'
    count: 10
    exact: false

# run the program and confirm correct number of lines in the output
- description: Run the calculate algorithm and confirm the correct number of non-blank lines in the benchmark output
  check: CountCommandOutput
  options:
    command: 'cd lcsfinder && poetry run lcsfinder --algorithmtype calculate --startsize 1 --runs 2 --datatype ints --strategy double'
    count: 10
    exact: false

# }}}

# Commits {{{

# count number of commits in the GitHub repository
- description: Have at least a specific minimum of commits in repository
  check: CountCommits
  options:
    count: 10

# }}}
